{
 "title": "Router - Wireless Clients",
 "tags": [ "router_wl" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "import \"influxdata/influxdb/v1\"\r\nv1.tagValues(\r\n    bucket: \"test\",\r\n    tag: \"hostname\",\r\n    predicate: (r) => true,\r\n    start: -1d\r\n)"
   },
   {
    "name": "ip",
    "label": "IP",
    "query": "from(bucket: \"test\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"router_asus_wificlients\")\n  |> filter(fn: (r) => r[\"hostname\"] == \"${hostname}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> distinct(column: \"ip\")\n  |> keep(columns: [\"_value\"])\n  |> yield(name: \"last\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Time Online",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"test\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) =>\n        r._measurement == \"router_asus_wificlients\" and\n        r.hostname == \"${hostname}\" and \n        r.ip == \"${ip}\" and\n        (r._field == \"online\")\n        )\n//    |> derivative(unit: 1s, nonNegative: true)\n    |> drop(columns: [\"host\", \"ip\", \"wifi\", \"wifiBand\"])\n    |> aggregateWindow(every: v.windowPeriod, fn: mean)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Time Idle",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"test\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) =>\n        r._measurement == \"router_asus_wificlients\" and\n        r.hostname == \"${hostname}\" and \n        r.ip == \"${ip}\" and\n        (r._field == \"idle\")\n        )\n//    |> derivative(unit: 1s, nonNegative: true)\n    |> drop(columns: [\"host\", \"ip\", \"wifi\", \"wifiBand\"])\n    |> aggregateWindow(every: v.windowPeriod, fn: mean)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "📶 WiFi Band",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"test\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) =>\n        r._measurement == \"router_asus_wificlients\" and\n        r.hostname == \"${hostname}\" and \n        r.ip == \"${ip}\" \n        )\n    |> drop(columns: [\"_value\"])\n    |> rename(columns: {wifiBand: \"_value\"})\n    |> keep(columns: [\"_value\", \"_time\"])\n    |> aggregateWindow(every: v.windowPeriod, fn: last)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "📶 Link Bandwidth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"test\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) =>\n        r._measurement == \"router_asus_wificlients\" and\n        r.hostname == \"${hostname}\" and \n        r.ip == \"${ip}\" and\n        (r._field == \"link_bandwidth\")\n        )\n//    |> derivative(unit: 1s, nonNegative: true)\n    |> drop(columns: [\"host\", \"ip\", \"wifi\", \"wifiBand\"])\n    |> aggregateWindow(every: v.windowPeriod, fn: last)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tx Failures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"test\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) =>\n        r._measurement == \"router_asus_wificlients\" and\n        r.hostname == \"${hostname}\" and \n        r.ip == \"${ip}\" and\n        (r._field == \"tx_failures\")\n        )\n//    |> derivative(unit: 1s, nonNegative: true)\n    |> drop(columns: [\"host\", \"ip\", \"wifi\", \"wifiBand\"])\n    |> aggregateWindow(every: v.windowPeriod, fn: last)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rx Decrypt Failures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"test\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) =>\n        r._measurement == \"router_asus_wificlients\" and\n        r.hostname == \"${hostname}\" and \n        r.ip == \"${ip}\" and\n        (r._field == \"rx_decrypt_failures\")\n        )\n//    |> derivative(unit: 1s, nonNegative: true)\n    |> drop(columns: [\"host\", \"ip\", \"wifi\", \"wifiBand\"])\n    |> aggregateWindow(every: v.windowPeriod, fn: last)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": {
    "content": "<center><img src=\"https://dlcdnwebimgs.asus.com/gain/55ce4cd4-b7f9-4bf6-854b-fdc567958f4c/\" style=\"width:78%\" /></center>\n         "
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "🔽 Rx Traffic",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 35 }
   ]
  },
  {
   "title": "📡 Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"test\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) =>\r\n        r._measurement == \"router_asus_wificlients\" and\r\n        r.hostname == \"${hostname}\" and \r\n        r.ip == \"${ip}\" and\r\n        r._field == \"rx_total_bytes\"\r\n        )\r\n    |> derivative(unit: 1s, nonNegative: true)\r\n    |> drop(columns: [\"host\", \"ip\", \"wifi\", \"wifiBand\"])\r\n    |> aggregateWindow(every: v.windowPeriod, fn: mean)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"test\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) =>\r\n        r._measurement == \"router_asus_wificlients\" and\r\n        r.hostname == \"${hostname}\" and \r\n        r.ip == \"${ip}\" and\r\n        r._field == \"tx_total_bytes\"\r\n        )\r\n    |> derivative(unit: 1s, nonNegative: true)\r\n    |> drop(columns: [\"host\", \"ip\", \"wifi\", \"wifiBand\"])\r\n    |> aggregateWindow(every: v.windowPeriod, fn: mean)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "🔼 Tx Traffic",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 35 }
   ]
  },
  {
   "title": "Client Download Since Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"test\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) =>\r\n        r._measurement == \"router_asus_wificlients\" and\r\n        r.hostname == \"${hostname}\" and \r\n        r.ip == \"${ip}\" and\r\n        r._field == \"tx_total_bytes\"\r\n        )\r\n        |> aggregateWindow(every: v.windowPeriod, fn: mean)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"test\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) =>\r\n        r._measurement == \"router_asus_wificlients\" and\r\n        r.hostname == \"${hostname}\" and \r\n        r.ip == \"${ip}\" and\r\n        (r._field == \"rssi\")\r\n        )\r\n    |> drop(columns: [\"host\", \"ip\", \"wifi\", \"wifiBand\"])\r\n    |> aggregateWindow(every: v.windowPeriod, fn: mean)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Client Upload Since Up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"test\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) =>\r\n        r._measurement == \"router_asus_wificlients\" and\r\n        r.hostname == \"${hostname}\" and \r\n        r.ip == \"${ip}\" and\r\n        r._field == \"rx_total_bytes\"\r\n        )\r\n    |> aggregateWindow(every: v.windowPeriod, fn: mean)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "📡 Received Signal Strength Indicator (RSSI)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"test\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) =>\r\n        r._measurement == \"router_asus_wificlients\" and\r\n        r.hostname == \"${hostname}\" and \r\n        r.ip == \"${ip}\" and\r\n        (r._field == \"rssi_antenna1\" or r._field == \"rssi_antenna2\" or r._field == \"rssi_antenna3\" or r._field == \"rssi_antenna4\") and\r\n        r._value < 0\r\n        )\r\n//    |> derivative(unit: 1s, nonNegative: true)\r\n    |> drop(columns: [\"host\", \"ip\", \"wifi\", \"wifiBand\"])\r\n    |> aggregateWindow(every: v.windowPeriod, fn: mean)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "📡 Noise",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"test\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) =>\r\n        r._measurement == \"router_asus_wificlients\" and\r\n        r.hostname == \"${hostname}\" and \r\n        r.ip == \"${ip}\" and\r\n        (r._field == \"noise_antenna1\" or r._field == \"noise_antenna2\" or r._field == \"noise_antenna3\" or r._field == \"noise_antenna4\") and\r\n        r._value < 0\r\n        )\r\n//    |> derivative(unit: 1s, nonNegative: true)\r\n    |> drop(columns: [\"host\", \"ip\", \"wifi\", \"wifiBand\"])\r\n    |> aggregateWindow(every: v.windowPeriod, fn: mean)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "📡 Received Signal Strength Indicator (RSSI) - Average",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"test\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) =>\r\n        r._measurement == \"router_asus_wificlients\" and\r\n        r.hostname == \"${hostname}\" and \r\n        r.ip == \"${ip}\" and\r\n        (r._field == \"rssi_antenna1_avg\" or r._field == \"rssi_antenna2_avg\" or r._field == \"rssi_antenna3_avg\" or r._field == \"rssi_antenna4_avg\") and\r\n        r._value < 0\r\n        )\r\n//    |> derivative(unit: 1s, nonNegative: true)\r\n    |> drop(columns: [\"host\", \"ip\", \"wifi\", \"wifiBand\"])\r\n    |> aggregateWindow(every: v.windowPeriod, fn: mean)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "📡 Last Packet Transmission Speed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"test\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) =>\r\n        r._measurement == \"router_asus_wificlients\" and\r\n        r.hostname == \"${hostname}\" and \r\n        r.ip == \"${ip}\" and\r\n        r._field == \"rx_rate_pkt\"\r\n        )\r\n//    |> derivative(unit: 1s, nonNegative: true)\r\n    |> drop(columns: [\"host\", \"ip\", \"wifi\", \"wifiBand\"])\r\n    |> aggregateWindow(every: v.windowPeriod, fn: mean)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"test\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) =>\r\n        r._measurement == \"router_asus_wificlients\" and\r\n        r.hostname == \"${hostname}\" and \r\n        r.ip == \"${ip}\" and\r\n        r._field == \"tx1_rate_pkt\"\r\n        )\r\n//    |> derivative(unit: 1s, nonNegative: true)\r\n    |> drop(columns: [\"host\", \"ip\", \"wifi\", \"wifiBand\"])\r\n    |> aggregateWindow(every: v.windowPeriod, fn: mean)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"test\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) =>\r\n        r._measurement == \"router_asus_wificlients\" and\r\n        r.hostname == \"${hostname}\" and \r\n        r.ip == \"${ip}\" and\r\n        r._field == \"tx2_rate_pkt\"\r\n        )\r\n//    |> derivative(unit: 1s, nonNegative: true)\r\n    |> drop(columns: [\"host\", \"ip\", \"wifi\", \"wifiBand\"])\r\n    |> aggregateWindow(every: v.windowPeriod, fn: mean)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}